import { Inter } from "next/font/google";
import "./globals.css";
import CustomNavbar from "./components/CustomNavbar";
import CustomFooter from "./components/CustomFooter";
import "react-toastify/dist/ReactToastify.css";
import { ToastContainer } from "react-toastify";
import UserProvider from "@/context/UserProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Home : Work Manager",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <UserProvider>
          <ToastContainer />
          {/* <div className="sticky top-0"> */}
          <CustomNavbar />
          {/* </div> */}
          {children}
          <CustomFooter />
        </UserProvider>
      </body>
    </html>
  );
}
